# Agenda

1. Numpy
2. Array
3. Working with NumPy
4. Difference between NumPy and Array
5. NumPy Array
6. How to Create NumPy Array
7. Operation on NumPy: Slicing
8. Join in an Array

# NumPy


+ An acronym for **"Numerical Python"**
+ Python library for scientific computing application
+ fast mathematical computation on array and matrices
+ ndarray (n-dimensional array) objects
+ [Numpy Reference](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

## Array

+ Container that hold fixed number of items
+ Items have same data type
+ Contiguous (one after the other) location holding the elements

### An array consists of:

+ **Element**: Each item stored in an array is called an element.

+ **Index**: Each location of an element in an array has a numerical index, which is used to identify the element.

#### Array Representation

![array](https://media.geeksforgeeks.org/wp-content/uploads/C-Arrays.jpg)

### Anatomy of an Array

![a-array](https://i.imgur.com/mg8O3kd.png)


### Terms

1. **Axes**:  ***axis = 0*** ( row-wise) and ***axis = 1*** (column-wise)
2. **Rank**: Number of axes it possesses.

> **Rank = Number of axes**

3. **Shape**: Number of elements it contains along each of its axis.

###### Array Representation in a language (C++)

Arrays can be declared in various ways in different languages. Given below is an illustration:

![array-1](https://www.tutorialspoint.com/data_structures_algorithms/images/array_declaration.jpg)  

![array-2](https://www.tutorialspoint.com/data_structures_algorithms/images/array_representation.jpg)


<hr>

## Working with NumPy

1. Install the numpy on your PC

```python
pip install numpy
```
2. Import Numpy

```python
import numpy as np
```
3. Now, you are ready to use NumPy

### Numpy Arrays

1. **One-dimesional (1D) Array**: An array of dimension one is called one-dimesional array. It is also known as **Vector**.

![1D](https://miro.medium.com/max/3000/1*qlRqv3c89DK7lw6pihnPhw.jpeg)

2. **Multidimensional arrays or ndarrays**: An array of n-dimension is called ndarray. It is also known as **Matrices**

![ND](https://media.geeksforgeeks.org/wp-content/uploads/two-d.png)

### Difference between NumPy Array and List

| NumPy Array                                                     | List                                                            |
| --------------------------------------------------------------- | --------------------------------------------------------------- |
| NumPy array works on homogeneous (same) types.                  | Python lists are made up of heterogeneous (different) types     |
| NumPy array does not support addition and removal of elements   | Python lists supports adding and removal of elements            |
| Can't contain elements of different types                       | Can contain elements of different types                         |
| Less memory consumption                                         | More memory consumption                                         |
| Faster runtime execution                                        | Runtime execution is comparatively slower than arrays           |

<hr>

## How to CREATE A NumPy ARRAY


There are several ways of creating a NumPy array.

+  **np.array()**: To create 1D/2D NumPy array
+  **np.fromstring()**: To create 1D array from string
3. **np.empty()**: An empty array or uninitialized array
4. **np.zeros()**: New array with all elements as zeroes
5. **np.ones()**: New array with all ones as its elements
6. **np.arange()**: Used to create array from a range
7. **np.linspace()**: To create array of range
8. **np.copy()**: Used to create a copy of an existing array
9. **np.reshape()**: We can create 2D array from 1D array
10. **np.eye() or np.identity()**: All diagonals value will be one

### array()

In [4]:
#To create a one-dimensional array

import numpy as np

l1 = [2,3,4,5,6]
arr1 = np.array(l1)

print(arr1)

[2 3 4 5 6]


In [5]:
#To create a two-dimesional array
import numpy as np

A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### fromstring()

In [6]:
import numpy as np

data = np.fromstring('1 2 3 4 10 12 13', dtype = int, sep = " ")
print(data)

[ 1  2  3  4 10 12 13]


### empty()

In [16]:
import numpy as np

arr = np.empty( [3,2], dtype = int, order = 'F')  # default order: C
print(arr)

[[0 0]
 [0 0]
 [0 0]]


### zeros()

In [15]:
# array of five zeros. Default type is float

import numpy as np

arr1 = np.zeros(5)
print(arr1)

[0. 0. 0. 0. 0.]


### ones()

In [17]:
# array of five ones. Default dtype is float

import numpy as np

arr1 = np.ones(5)
print(arr1)

[1. 1. 1. 1. 1.]


### arange()

![Image](https://miro.medium.com/max/679/1*16lfH-A_kiDmyxe1Sm2dQA.png)

In [32]:
import numpy as np

a1 = np.arange(1,13)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


### linspace()

In [1]:
import numpy as np

line = np.linspace(1,10,10)
print(line)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


### copy()

In [21]:
import numpy as np
x = np.array([1,2,3])
y = x
z = np.copy(x)
x[0] = 10

print(x)
print(y)
print(z)

[10  2  3]
[10  2  3]
[1 2 3]


### reshape()

Reshaping means changing the arrangement of items so that the shape of the array changes while maintaining the same number of dimensions.

1D
![Image](https://miro.medium.com/max/679/1*16lfH-A_kiDmyxe1Sm2dQA.png)

Reshaped into (2D)
![reshape](https://miro.medium.com/max/251/1*b0Eh1M1w4d9gKIhN8Fdjcg.png)

In [38]:
import numpy as np

a1 = np.arange(1,13)
reshape = a1.reshape(3,4)

print("1D: array\n", a1)
print("\nAfter Reshaped (2D): \n", reshape)

1D: array
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

After Reshaped (2D): 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
reshape = a1.reshape(3,4, order = 'F')
reshape

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [23]:
# Creating of 2D array from 1D array using reshape() function

import numpy as np

A = np.array([1,2,3,4,5,6])
print(A)

print("-------------")

B = np.reshape(A, (2,3)) #reshape shall convert 1D array into 2D array with 2 rows and 3 columns
print(B)

[1 2 3 4 5 6]
-------------
[[1 2 3]
 [4 5 6]]


### eye() / identity()

In [29]:
# create a 4x4 identity matrix using the eye method
import numpy as np

# 4x4 matrix wil 1's as all diagonal elements
mat1 = np.identity(4)
print("\nMatrix 1: \n", mat1)


Matrix 1: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
#Alternatively

mat2 = np.eye(4, dtype = float)
print("\nMatrix 2: \n", mat2)


Matrix 2: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


<hr>

## Operations ON NumPy 

#### Array Slicing

+ Slicing means sub-sequence of the structure can be indexed and retrieved.
+ Slicing is specified by using the colon operator `:` with a `from` and `to`.
+ **data[from:to]**

### Slicing in 1D Array

In [41]:
# Slicing in 1D array

import numpy as np
data = np.array([5,2,7,3,9])

print(data[:])   #Shall extract slice from start to end

[5 2 7 3 9]


In [46]:
print(data[1:3])  #Shall extract slice from 1st position to 4th, excluding the 4th position

[2 7]


In [47]:
print(data[:2])

[5 2]


In [48]:
print(data[-2:])

[3 9]


### Slicing in 2D array

![slice-2d](https://learning.oreilly.com/api/v2/epubs/urn:orm:book:9781449323592/files/httpatomoreillycomsourceoreillyimages2172114.png)

In [52]:
# Slicing in 2D array

import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
print(arr[:2, 1:])

[[2 3]
 [5 6]]


In [55]:
print(arr[2])
print(arr[2, :])
print(arr[2:, :])

[7 8 9]
[7 8 9]
[[7 8 9]]


In [56]:
print(arr[:, :2])

[[1 2]
 [4 5]
 [7 8]]


In [57]:
print(arr[1, :2])
print(arr[1:2, :2])

[4 5]
[[4 5]]


In [60]:
# Another example of Slicing

import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [61]:
b = a[1:2, 0:4]
print(b)

[[5 6 7 8]]


In [62]:
b = a[1:2,1:2]
print(b)

[[6]]


In [63]:
b = a[:2, 0:2]
print(b)

[[1 2]
 [5 6]]


In [64]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [65]:
b = a[1:3, 2:4]
print(b)

[[ 7  8]
 [11 12]]


<hr>

## Joins in Arrays

Joining of two arrays in NumPy is done using **concatenate()** function.

This function is used to join two or more arrays of the same shape.

**Note**

In case of a 2D array, this function concatenates two arrays either by rows or by columns.

In [1]:
#Concatenating two 1D arrays

import numpy as np

a = np.array([1,2,3])
b = np.array([5,6])

c = np.concatenate([a,b,a])
print(c)

[1 2 3 5 6 1 2 3]


In [3]:
#Concatenating two 2D arrays using single array

import numpy as np

A = np.array([[7,5], [1,6]])

## concatenate along the first axis
print("\nAlong First Axis")
print(np.concatenate([A,A]))

## concatenate along the second axis (zero-indexed)
print("\nAlong Second Axis")
print(np.concatenate([A,A], axis = 1))



Along First Axis
[[7 5]
 [1 6]
 [7 5]
 [1 6]]

Along Second Axis
[[7 5 7 5]
 [1 6 1 6]]


In [7]:
x = np.array([1,2])

# vertically stack the arrays
print("Vertical Stack")
print(np.vstack([x, A]))
      
# horizontally stack the arrays
print("\nHorizontal Stack")
y = np.array([[99], [99]])
print(np.hstack([A, y]))

Vertical Stack
[[1 2]
 [7 5]
 [1 6]]

Horizontal Stack
[[ 7  5 99]
 [ 1  6 99]]


## Vertical Stack

![vstack](https://www.tutorialsandyou.com/images/1-Dimensional-vertical-stacking.jpg)

In [14]:
a = np.array([[1,2],[2,4]])
b = np.array([[7,8]])

c = np.concatenate((a,b), axis = 0)
print(c)

[[1 2]
 [2 4]
 [7 8]]


In [9]:
np.vstack([a,b])

array([[1, 2],
       [2, 4],
       [7, 8]])

## Horizontal Stack

![hstack](https://www.tutorialsandyou.com/images/1-Dimensional-horizontal-stacking.jpg)

In [11]:
a = np.array([[1,2],[2,4]])
b = np.array([[7,8]])

c = np.concatenate((a,b.T), axis = 1)
print(c)

[[1 2 7]
 [2 4 8]]


In [13]:
np.hstack([a,b.T])

array([[1, 2, 7],
       [2, 4, 8]])

<hr>

![Image](https://miro.medium.com/max/4024/1*lFZzE9PgKTRR8jlFI4EUtw.png)

Reference:
1. https://towardsdatascience.com/reshaping-numpy-arrays-in-python-a-step-by-step-pictorial-tutorial-aed5f471cf0b